apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-app-of-apps
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/ikaratsoris/argocd-test
    targetRevision: HEAD
    path: cicd-cluster/apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
